[versions]
agp = "8.9.3"
androidTest = "1.7.0"
kotlin = "2.2.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.10.01"
datastore = "1.2.0"
media3 = "1.8.0"
sqliteVersion = "2.6.2"
taglib = "1.0.0-alpha25"
kotlinxSerialization = "1.9.0"
kotlinxCoroutines = "1.10.2"
nav = "2.9.1"
common-codec = "1.19.0"
coil = "3.3.0"
#sqlite = '3.49.0'
material3 = "1.8.0"
materialIcons = "1.7.0"
composeHotReload = "1.0.0-rc02"
composeMultiplatform = "1.9.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
ktor = "3.2.2"
kodeinVersion = "7.28.0"
okioVersion = "3.16.0"
kotlinCryptoVersion = "0.8.0"
rwLockVersion = "1.0.0"
jetbrainsKotlinJvm = "2.2.10"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin"}
rwLock = { group = "com.mayakapps.rwmutex", name = "rwmutex", version.ref = "rwLockVersion" }
androidx-runner = { module = "androidx.test:runner", version.ref = "androidTest" }
androidx-core = { module = "androidx.test:core", version.ref = "androidTest" }
androidx-rules = { module = "androidx.test:rules", version.ref = "androidTest" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqliteVersion" }
#sqlite = { group = 'com.github.requery', name = 'sqlite-android', version.ref = 'sqlite' }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
taglib = { group = "com.github.Kyant0", name = "taglib", version.ref = "taglib" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3"}
androidx-material3-icons = { group = "org.jetbrains.compose.material", name = "material-icons-core", version.ref = "materialIcons" }
#androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization"}
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines"}
navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "nav" }
commons-codec = { group = "commons-codec", name="commons-codec", version.ref="common-codec" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-curl = { group = "io.ktor", name = "ktor-client-curl", version.ref = "ktor" }
ktor-client-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktor-client-winhttp = { group = "io.ktor", name = "ktor-client-winhttp", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-resources = { group = "io.ktor", name = "ktor-server-resources", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }

ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio", version.ref="ktor" }
kodein-core = { group = "org.kodein.di", name = "kodein-di", version.ref = "kodeinVersion" }
kodein-compose = { group = "org.kodein.di", name = "kodein-di-framework-compose", version.ref = "kodeinVersion" }
kodein-iosArm64 = { group = "org.kodein.di", name = "kodein-di-iosarm64", version.ref = "kodeinVersion" }
kodein-iosX64 = { group = "org.kodein.di", name = "kodein-di-iosx64", version.ref = "kodeinVersion" }
kodein-iosSimulatorArm64 = { group = "org.kodein.di", name = "kodein-di-iossimulatorarm64", version.ref = "kodeinVersion" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okioVersion" }
kotlinCrypto-md = { group = "org.kotlincrypto.hash", name = "md", version.ref = "kotlinCryptoVersion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
#jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
#parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

#androidApplication = { id = "com.android.application", version.ref = "agp" }
#androidLibrary = { id = "com.android.library", version.ref = "agp" }

